In [1]:
import pandas as pd
import re

In [2]:
all_trails = pd.read_pickle('all_trails_complete.pkl')

In [3]:
all_trails.dropna(how = 'any', inplace=True)

In [4]:
all_trails.shape

(999, 10)

In [5]:
all_trails = all_trails.reset_index(drop = True)

In [6]:
all_trails.head()

,trail_name,difficulty,distance,elevation_gain,route_type,num_completed,activities,photos,reviews,tags
0,Rattlesnake Ledge Trail,moderate,5.3 mi,"1,459 ft",Out & back,"Completed (22,795)","Activities (8,670)","Photos (6,476)","Reviews (9,438)","[Dogs on leash, Kid friendly, Hiking, Forest, ..."
1,Skyline Trail Loop,hard,6.2 mi,"1,788 ft",Loop,"Completed (13,196)","Activities (4,888)","Photos (13,810)","Reviews (5,633)","[Backpacking, Hiking, Forest, Partially paved,..."
2,Snow Lake Trail,moderate,6.7 mi,"1,699 ft",Out & back,"Completed (14,324)","Activities (5,398)","Photos (7,610)","Reviews (6,223)","[Dogs on leash, Backpacking, Camping, Hiking, ..."
3,Lake 22 Trail,moderate,6.8 mi,"1,473 ft",Loop,"Completed (15,185)","Activities (4,519)","Photos (7,134)","Reviews (5,970)","[Dogs on leash, Hiking, Snowshoeing, Running, ..."
4,Colchuck Lake via Stuart Lake Trail,hard,9.0 mi,"2,283 ft",Out & back,"Completed (10,614)","Activities (3,807)","Photos (5,536)","Reviews (4,584)","[Backpacking, Camping, Hiking, Snowshoeing, Ru..."

In [7]:
all_trails[['distance', 'elevation_gain', 'activities', 'photos', 'reviews', 'num_completed']] = all_trails[['distance', 'elevation_gain', 'activities','photos','reviews', 'num_completed']].replace(to_replace='[^\d\.]', value='', regex=True)

In [8]:
all_trails[['distance', 'elevation_gain', 'activities', 'photos', 'reviews', 'num_completed']] = all_trails[['distance', 'elevation_gain', 'activities', 'photos', 'reviews','num_completed']].astype('float')

In [9]:
all_trails.head()

,trail_name,difficulty,distance,elevation_gain,route_type,num_completed,activities,photos,reviews,tags
0,Rattlesnake Ledge Trail,moderate,5.3,1459.0,Out & back,22795.0,8670.0,6476.0,9438.0,"[Dogs on leash, Kid friendly, Hiking, Forest, ..."
1,Skyline Trail Loop,hard,6.2,1788.0,Loop,13196.0,4888.0,13810.0,5633.0,"[Backpacking, Hiking, Forest, Partially paved,..."
2,Snow Lake Trail,moderate,6.7,1699.0,Out & back,14324.0,5398.0,7610.0,6223.0,"[Dogs on leash, Backpacking, Camping, Hiking, ..."
3,Lake 22 Trail,moderate,6.8,1473.0,Loop,15185.0,4519.0,7134.0,5970.0,"[Dogs on leash, Hiking, Snowshoeing, Running, ..."
4,Colchuck Lake via Stuart Lake Trail,hard,9.0,2283.0,Out & back,10614.0,3807.0,5536.0,4584.0,"[Backpacking, Camping, Hiking, Snowshoeing, Ru..."

In [10]:
all_trails.dtypes

trail_name         object
difficulty         object
distance          float64
elevation_gain    float64
route_type         object
num_completed     float64
activities        float64
photos            float64
reviews           float64
tags               object
dtype: object

In [11]:
all_trails['tags'] = all_trails['tags'].apply(', '.join)

In [12]:
all_trails['dogs'] = all_trails.tags.str.contains('Dogs on leash').astype('int')
all_trails['views'] = all_trails.tags.str.contains('Views').astype('int')
all_trails['kids'] = all_trails.tags.str.contains('Kid friendly').astype('int')
all_trails['fee'] = all_trails.tags.str.contains('Fee').astype('int')
all_trails['wildlife'] = all_trails.tags.str.contains('Wildlife').astype('int')
all_trails['lake'] = all_trails.tags.str.contains('Lake').astype('int')
all_trails['beach'] = all_trails.tags.str.contains('Beach').astype('int')
all_trails['wildflowers'] = all_trails.tags.str.contains('Wildflowers').astype('int')
all_trails['rocky'] = all_trails.tags.str.contains('Rocky').astype('int')
all_trails['loop'] = all_trails.route_type == 'Loop'
all_trails.loop = all_trails.loop.astype('int')
all_trails = pd.get_dummies(all_trails, columns = ['difficulty'], drop_first = True)

In [13]:
all_trails.head()

,trail_name,distance,elevation_gain,route_type,num_completed,activities,photos,reviews,tags,dogs,...,kids,fee,wildlife,lake,beach,wildflowers,rocky,loop,difficulty_hard,difficulty_moderate
0,Rattlesnake Ledge Trail,5.3,1459.0,Out & back,22795.0,8670.0,6476.0,9438.0,"Dogs on leash, Kid friendly, Hiking, Forest, L...",1,...,1,0,1,1,0,1,1,0,0,1
1,Skyline Trail Loop,6.2,1788.0,Loop,13196.0,4888.0,13810.0,5633.0,"Backpacking, Hiking, Forest, Partially paved, ...",0,...,0,1,1,0,0,1,1,1,1,0
2,Snow Lake Trail,6.7,1699.0,Out & back,14324.0,5398.0,7610.0,6223.0,"Dogs on leash, Backpacking, Camping, Hiking, S...",1,...,0,0,1,1,0,1,1,0,0,1
3,Lake 22 Trail,6.8,1473.0,Loop,15185.0,4519.0,7134.0,5970.0,"Dogs on leash, Hiking, Snowshoeing, Running, F...",1,...,0,0,1,1,0,1,1,1,0,1
4,Colchuck Lake via Stuart Lake Trail,9.0,2283.0,Out & back,10614.0,3807.0,5536.0,4584.0,"Backpacking, Camping, Hiking, Snowshoeing, Run...",0,...,0,1,1,1,0,1,1,0,1,0

In [14]:
all_trails.drop(columns = ['route_type','tags'], inplace = True)

In [15]:
all_trails.head()

,trail_name,distance,elevation_gain,num_completed,activities,photos,reviews,dogs,views,kids,fee,wildlife,lake,beach,wildflowers,rocky,loop,difficulty_hard,difficulty_moderate
0,Rattlesnake Ledge Trail,5.3,1459.0,22795.0,8670.0,6476.0,9438.0,1,1,1,0,1,1,0,1,1,0,0,1
1,Skyline Trail Loop,6.2,1788.0,13196.0,4888.0,13810.0,5633.0,0,1,0,1,1,0,0,1,1,1,1,0
2,Snow Lake Trail,6.7,1699.0,14324.0,5398.0,7610.0,6223.0,1,1,0,0,1,1,0,1,1,0,0,1
3,Lake 22 Trail,6.8,1473.0,15185.0,4519.0,7134.0,5970.0,1,1,0,0,1,1,0,1,1,1,0,1
4,Colchuck Lake via Stuart Lake Trail,9.0,2283.0,10614.0,3807.0,5536.0,4584.0,0,1,0,1,1,1,0,1,1,0,1,0

In [16]:
all_trails.to_pickle('cleaned_trails.pkl')